services:
  algorithm:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./algorithm:/app/algorithm
      - ./web:/app/web
    environment:
      - PYTHONPATH=.
    command: flask --app web.app run --host=0.0.0.0