services:
  algorithm:
    build: .
    ports:
      - 5000:8000
    volumes:
      - ./algorithm:/app/algorithm
      - ./web:/app/web
    environment:
      - PYTHONPATH=.
    command: gunicorn -b 0.0.0.0 --reload 'web.app:app'